config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "about-us" => "static_pages#about_us"
  get "research" => "static_pages#research"
  get "our-approach" => "static_pages#our_approach"
  get "results" => "static_pages#results"
  get "terms-of-use" => "static_pages#terms_of_use"
  get "privacy-policy" => "static_pages#privacy_policy"

  controller :blog do
    get "blog" => :index
    get "blog/first-harlem-spelling-bee" => :june_19_2017_first_harlem_spelling_bee
    get "blog/six-words-that-dont-mean-what-you-think" => :june_19_2017_six_words_that_dont_mean_what_you_think
    get "blog/about-our-name" => :june_19_2017_about_our_name
  end

  controller :spelling_bee do
    get "spelling-bee" => :index
    get "spelling-bee/about" => :about
    get "spelling-bee/competition" => :competition
    get "spelling-bee/teachers" => :teachers
    get "spelling-bee/sponsors" => :sponsors
    get "spelling-bee/contact-us" => :contact_us
  end

  get "feedback" => "current_users#feedback"
  get "dictionary" => "searches#dictionary"
  get "searches/section"
  get "searches/random"
  get "search_results" => "searches#results"
  get "stats" => "current_users#stats"
  get "freestyles" => "current_users#freestyles"
  get "notebook" => "my_leksi#index"
  get "my_leksi/words"
  get "myLeksi/:id" => "my_leksi#show"
  get "gamezone" => "games#gamezone"
  get "fundamentals" => "games#fundamentals"
  get "jeopardy" => "games#jeopardy"
  get "freestyle" => "games#freestyle"
  get "games/new"
  get "signup" => "users#new"
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  post "static_pages/contact_us"
  post "games/email_freestyle"
  delete "logout" => "sessions#destroy"
  resources :users, except: [:index]
  resources :words, only: [:show]

  resources :words do
    resources :examples
  end

  get "thesaurus/:word_name" => "words#thesaurus"

  resources :words do
    resources :meaning_alts, only: [:index]
  end

  resources :words do
    resources :example_non_examples, only: [:index]
  end

  resources :words do
    resources :sent_stems, only: [:index]
  end

  resource :user_word, only: [:create, :update, :destroy]
  resource :jeopardy_game, only: [:create, :update, :destroy]

  resource :freestyle do
    member do
      post "ex_non_ex"
      post "sent_stem"
      post "word_rel"
      post "leksi_tale"
      post "describe_me"
      post "in_my_life"
    end
  end

  resource :game_stat do
    member do
      post "generic_game"
    end
  end

  resource :jeopardy_result, only: [:update]
  resources :tags, only: [:index]
  resource :user_tag, only: [:create, :edit, :destroy]
  resource :word_tag, only: [:create, :destroy]
  resource :user_word_tag, only: [:create, :edit, :destroy]

  namespace :games do
    resources :word_relationships, only: [:index]
    resources :describe_mes, only: [:index]
    resources :spellmasters, only: [:index]
  end

  namespace :school do
    root "classrooms#index"
    get "example_non_examples/fourth" => "example_non_examples#fourth_grade"
    get "decisions_decisions/fourth" => "meaning_alts#fourth_grade"
    get "example_non_examples/second" => "example_non_examples#second_grade"
    get "example_non_examples/fifth" => "example_non_examples#fifth_grade"
    get "example_non_examples/sixth" => "example_non_examples#sixth_grade"
    get "search" => "searches#search"
    get "search_words_for_students" => "searches#student_words"
    get "stats" => "stats#index"
    get "add_words" => "students#add_words"

    resources :activities, only: [:index]

    resources :classrooms do
      resources :students
    end

    resources :words, except: [:show, :destroy]
    resource :add_words_for_student, only: [:update]
    resource :reset_passwords, only: [:update]

    resources :example_non_examples

    resources :word do
      resources :example_non_examples
    end

    resources :meaning_alts

    resources :word do
      resources :meaning_alts
    end

    resources :freestyles do
      resources :comments
    end

    resources :tags
  end

  namespace :admin do
    root "admins#home"
    get "home" => "admins#home"
    get "stats" => "admins#stats"
    resources :users
    resources :words
    resources :classrooms
    resources :meaning_alts
    resources :example_non_examples
    resources :tags
    resources :freestyles
  end
end

app/models/spelling_bee.rb
# TODO Create test
class SpellingBee
	attr_accessor :words

	def initialize(words)
		@words = words
	end

	def group_by_20
		words.shuffle.take(100).sort.each_slice(20).to_a.each do |group|
			group.each do |name|
				puts name
			end
			puts
		end

		# p _.flatten
	end

	def define_all
		no_good = []
		num_existing_words = 0
		num_errors = 0

		puts "Starting to define ??? Grade Words:"
		puts

		words.each do |name|
			if Word.word_exists?(name)
				puts "OK: \'#{name}\' already exists."
				num_existing_words += 1
			else
				words_api_search = WordsApi.new(name).define

				if words_api_search.class == String
					puts words_api_search
					no_good << { name: words_api_search }
					num_errors += 1
				else
					words_api_search.each do |new_word|
						if new_word.save
							puts "Success for word #{name}(#{new_word.id})"
						else
							num_errors += 1
							puts "ERROR for word #{name}: #{new_word.errors.full_messages}."
						end
					end
				end
			end
		end

		puts
		puts "Num words that already exist: #{num_existing_words}"
		puts
		puts "BAD WORDS (#{num_errors}): #{no_good}"
		puts
	end

	def retrieve_ids
		ids = []
		words.each { |name| ids << Word.where(name: name)[0].id }
		ids
		# p _
	end
end

app/controllers/spelling_bee_controller.rb
class SpellingBeeController < ApplicationController
  layout "application_spelling_bee"

  def index
  end

  def about
  end

  def competition
  end

  def teachers
  end

  def sponsors
  end

  def contact_us
  end
end

app/views/spelling_bee/_enroll.html.erb
<section class="spee-bee-trail-section" id="enroll">
	<div class="text-center container mb-4">
		<h4 class="spe-bee-redange">
			<%= icon "star" %> Leksi's 2nd Harlem Spelling Bee <%= icon "star" %>
		</h4>
		<% if controller?("spelling_bee") &&
					(action?("competition") || action?("about"))
		%>
			<%= render "spelling_bee/enroll_msg",
								 h1: "Enroll Students Today",
								 lead1: [
									 "Complete the form below to get started with enrollment ",
									 "(all fields are required)."
								 ].join,
								 lead2: [
									 "Please include your name and the names of all students ",
									 "who will "
								 ].join,
								 lead3: "be competing in the Message field below."
			%>
		<% elsif controller?("spelling_bee") && action?("teachers") %>
			<%= render "spelling_bee/enroll_msg",
								 h1: "Enroll Your School Today",
								 lead1: [
									 "Complete the form below to get started with enrollment ",
									 "(all fields are required). ",
								 ].join,
								 lead2: [
									 "Please include your school name, the grade(s) ",
									 "participating, and how many classrooms/students ",
								 ].join,
								 lead3: [
									 "will be competing in the Message field below."
								 ].join
			%>
		<% else %>
			<%= render "spelling_bee/enroll_msg",
								 h1: "Sponsor the Bee Today",
								 lead1: [
									 "Complete the form below to get started with sponsoring ",
									 "the Bee (all fields are required).",
								 ].join,
								 lead2: [
									 "Please include your business name and how you will ",
									 "contribute in the Message field below."
								 ].join,
								 lead3: ""
			%>
		<% end %>
	</div>
	<div class="container">
		<div class="row">
			<div class="col-md-8 mx-auto">
				<%= render "contact_us_mailer/form" %>
			</div>
		</div>
	</div>
</section>

app/views/spelling_bee/_enroll_msg.html.erb
<h1 class="display-3"><%= h1 %></h1>
<p class="lead">
	<%= lead1 %>
	<br>
	<%= lead2 %>
	<br>
	<%= lead3 %>
</p>

app/views/spelling_bee/_mailchimp.html.erb
<form action="//danelsonrosa.us3.list-manage.com/subscribe/post?u=4e5d4daffb8f0b6bc3364bc32&amp;id=e0d7d462de"
			method="post"
			id="mc-embedded-subscribe-form"
			name="mc-embedded-subscribe-form"
			class="validate mb-3"
			target="_blank"
			novalidate>
	<div id="mc_embed_signup_scroll">
		<div class="mc-field-group">
			<label for="mce-EMAIL" class="sr-only">Email Address</label>
			<input type="email"
						 value=""
						 name="EMAIL"
						 class="required email form-control"
						 id="mce-EMAIL"
						 placeholder="Email Address">
		</div>
		<div id="mce-responses" class="clear">
			<div class="response"
					 id="mce-error-response"
					 style="display:none"></div>
			<div class="response"
					 id="mce-success-response"
					 style="display:none"></div>
		</div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
		<div style="position: absolute; left: -5000px;"
				 aria-hidden="true">
			<input type="text"
						 name="b_4e5d4daffb8f0b6bc3364bc32_e0d7d462de"
						 tabindex="-1"
						 value="">
		</div>
		<div class="clear">
			<input type="submit"
						 value="Get the Latest News and Updates"
						 name="subscribe"
						 id="mc-embedded-subscribe"
						 class="btn btn-primary btn-block">
		</div>
	</div>
</form>

app/views/spelling_bee/about.html.erb
<% title "Harlem Spelling Bee - Learn about our History, Mission, and the Competition itself." %>
<% description "Promoting literacy and education in Harlem, we have high hopes for our students and exciting Bee competitions." %>
<% set_meta_tags keywords: %w[harlem spelling bee competition fun schools about history education vocabulary vocab literacy english language study dictionary words games notebook] %>

<% set_meta_tags og: {
  title: "Promoting literacy and education in Harlem, we have high hopes for our students and exciting Bee competitions.",
	description: "Designed with academic vocabulary research and gamification, Leksi helps students master new words."
} %>

<% set_meta_tags twitter: {
  card: "Which Harlem school students will become spelling bee champs?",
  title: "Promoting literacy and education in Harlem, we have high hopes for our students and exciting Bee competitions.",
  description: "It just takes one word to lead a lifetime of learning and growth."
} %>

<div class="container">
  <h1 class="display-4 spe-bee-redange mb-5">
    About the Bee
  </h1>
  <div class="row featurette">
    <div class="col-md-7">
      <h2 class="featurette-heading">The Power of Words</h2>
      <p>
        A good education can change a child’s future, and that education starts
        with the words they know. A student’s vocabulary size by grade 12 can
        affect the likelihood that they will graduate from college and the
        income they will earn in life. By giving them a chance to expand their
        vocabulary, the Harlem Spelling Bee can help students secure their
        future.
      </p>
    </div>
    <div class="col-md-5">
      <img class="featurette-image img-fluid mx-auto img-thumbnail"
           src="<%= asset_path('spelling-bee/leksi-about-the-bee-inaugural-winners.png') %>"
           alt="Generic placeholder image">
    </div>
  </div>
  <hr class="featurette-divider">
  <div class="row featurette">
    <div class="col-md-7 push-md-5">
      <h2 class="featurette-heading">Giving Students a Chance to Shine</h2>
      <p>
        The Harlem Spelling Bee fosters a fun and competitive learning
        environment that helps build each student’s reading and writing skills.
        This environment provides the contestants a chance to show off
        their academic ability and to be recognized for their hard work.
      </p>
      <p>
        Every student who is enrolled has the chance to become a champion.
      </p>
    </div>
    <div class="col-md-5 pull-md-7">
      <img class="featurette-image img-fluid mx-auto img-thumbnail"
           src="<%= asset_path('spelling-bee/leksi-our-mission.jpg') %>"
           alt="Generic placeholder image">
    </div>
  </div>
  <hr class="featurette-divider">
  <div class="row featurette">
    <div class="col-md-7">
      <h2 class="featurette-heading">Building the Harlem Community</h2>
      <p>
        One of the core beliefs of the Harlem Spelling Bee is the promotion of
        literacy and education within the Harlem Community. Children with access
        to the right educational opportunities have a higher chance of
        graduating from college and have a larger income potential. The Spelling
        Bee, powered by its sponsors and the
        <%= link_to "Leksi vocabulary and spelling app",
            root_path,
            title: "Learn more about the Leksi app"
        %>
        provides this
        opportunity to all schools within the Harlem community.
      </p>
      <p>
        Together, we have a chance to bring our home to greater heights than
        ever before.
      </p>
    </div>
    <div class="col-md-5">
      <img class="featurette-image img-fluid mx-auto img-thumbnail"
           src="<%= asset_path('spelling-bee/leksi-our-goals.jpg') %>"
           alt="Generic placeholder image">
    </div>
  </div>
  <hr class="featurette-divider">
  <div class="row featurette mb-3">
    <div class="col-md-7 push-md-5">
      <h2 class="featurette-heading">It’s More Than Just a Few Words</h2>
      <p>
        Contestants in the Spelling Bee learn far more than new vocabulary
        words. They learn just how important hard work is, and all the things
        they can accomplish when they set their mind to it and put forth strong
        and consistent effort. They learn that they
        have the opportunity to both change their lives and impact the world in
        ways they never thought possible.
      </p>
    </div>
    <div class="col-md-5 pull-md-7">
      <img class="featurette-image img-fluid mx-auto img-thumbnail"
           src="<%= asset_path('spelling-bee/leksi-about-the-bee-the-competition.jpg') %>"
           alt="Generic placeholder image">
    </div>
  </div>
  <%= render "spelling_bee/enroll" %>
</div>

app/views/spelling_bee/competition.html.erb
<% title "Harlem Spelling Bee - Learn about our History, Mission, and the Competition itself." %>
<% description "Promoting literacy and education in Harlem, we have high hopes for our students and exciting Bee competitions." %>
<% set_meta_tags keywords: %w[harlem spelling bee competition fun schools about history education vocabulary vocab literacy english language study dictionary words games notebook] %>

<% set_meta_tags og: {
  title: "Promoting literacy and education in Harlem, we have high hopes for our students and exciting Bee competitions.",
	description: "Designed with academic vocabulary research and gamification, Leksi helps students master new words."
} %>

<% set_meta_tags twitter: {
  card: "Which Harlem school students will become spelling bee champs?",
  title: "Promoting literacy and education in Harlem, we have high hopes for our students and exciting Bee competitions.",
  description: "It just takes one word to lead a lifetime of learning and growth."
} %>
<div class="competition jumbotron mb-3">
  <h1 class="display-3 mb-5">
    <b>2nd Harlem Spelling Bee</b>
    <p class="lead mt-4">
      The Spelling Bee is Broken into Two Rounds for the Competing Students
    </p>
  </h1>
  <div class="row">
    <div class="col-md-8 mx-auto">
      <h1 class="display-4">
        <small class="text-muted">Round 1</small>
        <br>
        The Preliminaries
      </h1>
      <p class="lead">
        <strong>
          This is an online exam that tests each student’s vocabulary. The
          Preliminaries are used to determine which students
          make it to the finals for the Main Event. The students who
          score the highest on this assessment will become Finalists.
        </strong>
      </p>
    </div>
    <div class="col-md-8 mx-auto">
      <hr class="featurette-divider">
      <h1 class="display-4">
        <small class="text-muted">Round 2</small>
        <br>
        Main Event
      </h1>
      <p class="lead mb-5">
        <strong>
          This is the exciting on-stage portion of the Harlem Spelling Bee. Known
          as the Main Event, the Finalists will prove their ability to
          spell words in front of an audience of their friends and family.
          This Main Event is what determines the top three winners, who will
          spell their way to victory one letter at a time.
        </strong>
      </p>
      <%= link_to "#",
                  role: "button",
                  title: "See more Harlem Spelling Bee Competition details",
                  class: "btn btn-outline-light mt-5 disabled" do %>
        <%= icon "long-arrow-down" %>
        see more details
        <%= icon "long-arrow-down" %>
      <% end %>
    </div>
  </div>
</div>
<div class="container">
  <div class="row marketing">
    <div class="col-lg-6">
      <h4><%= emoji "door" %> Registration</h4>
      <p>
        To enter the 2nd Harlem Spelling Bee, an adult
        for an elementary or middle school student (Grades 1-8) must enroll
        their student by completing the form down below.
      </p>
      <p>
        There are three different enrollment periods, i.e. Early Bird, Advanced,
        and Regular, when the adult can register. See the
        Timeline section below for the exact dates.
      </p>
      <p>
        High schoolers and adults, don't worry! There will be a Harlem Spelling
        Bee for you, too - stay tuned!
      </p>
      <h4><%= emoji "moneybag" %> Cost</h4>
      <p>
        <ul>
          <li>Regular Enrollment: $10 per student</li>
          <li>
            Schoolwide Enrollment:
            <%= link_to "please contact us",
                        spelling_bee_contact_us_path
            %>
            for special rates
          </li>
        </ul>
      </p>
      <h4><%= emoji "trophy" %> Prizes</h4>
      <p>
        The top three (3) winners will receive prizes.
        All Finalists will receive medals for their courage and effort
        in preparing for this big event.
      </p>
      <h4><%= emoji "clock3" %> Timeline</h4>
      <div class="activity-feed">
        <%= render "shared/activity_feed_item",
                   title: "Regular Enrollment Begins",
                   date: "Monday, February 26th, 2018",
                   text: ""
        %>
        <%= render "shared/activity_feed_item",
                   title: "2nd Harlem Spelling Bee Officially Begins",
                   date: "Monday, March 5th, 2018",
                   text: [
                     "This marks the beginning of the competition. All ",
                     "registered contestants from this point forward can ",
                     "begin using the online Leksi app to prepare ",
                     "for the Preliminaries."
                   ].join
        %>
        <%= render "shared/activity_feed_item",
                   title: "The Preliminaries",
                   date: "Tuesday, March 27th - Thursday, March 29th 2018",
                   text: [
                     "Contestants complete the online exam that will ",
                     "determine who advances to the ",
                     "next and final round, i.e. Main Event."
                   ].join
        %>
        <%= render "shared/activity_feed_item",
                   title: "Main Event Finalists Announced",
                   date: "Monday, April 2nd, 2018",
                   text: [
                     "The Finalists will be announced!"
                   ].join
        %>
        <%= render "shared/activity_feed_item",
                   title: "Main Event",
                   date: "Thursday, April 19th, 2018",
                   text: [
                     "This is what everyone has been waiting for - the ",
                     "actual on-stage spelling portion of the competition."
                   ].join
        %>
      </div>
    </div>
    <div class="col-lg-6">
      <h4><%= emoji "video_game" %> Leksi</h4>
      <p>
        Leksi is an online app that uses scientifically-backed methods to teach
        vocabulary and spelling in a fun environment. It is completely free for
        the duration of each Harlem Spelling Bee competition.
        <ul>
          <li>
            Students will use Leksi to prepare for the Preliminaries and
            Main Event by
            completing a variety of games and exercises. All activities were
            created following researched methods to ensure the students can
            learn and retain as they study
          </li>
          <li>
            Leksi will also provide the online exam for the Preliminaries.
            The top contestants who score the highest will become
            Finalists
          </li>
        </ul>
      </p>
      <h4><%= emoji "book" %> Words</h4>
      <p>
        The Preliminaries will feature a total word-bank of 300 words.
        All words can be found within the Leksi app and will already be in each
        students' account after they are registered.
      </p>
      <h4><%= emoji "muscle" %> Preparation</h4>
      <p>
        Using Leksi, the students will build their vocabulary and sharpen their
        spelling skills. Other tools that might help
        are vocabulary.com, Quizlet, or traditional methods like flashcards.
      </p>
      <h4><%= emoji "clipboard" %> Tips and Tricks</h4>
      <p>
        The National Spelling Bee has a great guide you can check out for handy
        tips:
        <%= link_to "How to Study for a Spelling Bee",
                    "http://spellingbee.com/sites/default/files/inline-files/How%20to%20Study%20for%20a%20Spelling%20Bee.pdf",
                    target: "_blank",
                    title: "National Spelling Bee Tips and Tricks"
        %>.
      </p>
    </div>
  </div>
  <%= render "spelling_bee/enroll" %>
</div>

app/views/spelling_bee/contact_us.html.erb
<% title "Harlem Spelling Bee - Promoting literacy and education in the Harlem community." %>
<% description "See how you can continue helping your students reach their full potential." %>
<% set_meta_tags keywords: %w[harlem spelling bee competition fun schools education vocabulary vocab literacy english language study dictionary words games notebook] %>

<% set_meta_tags og: {
  title: "See how you can continue helping your students reach their full potential.",
	description: "Designed with academic vocabulary research and gamification, Leksi helps students master new words."
} %>

<% set_meta_tags twitter: {
  card: "Which Harlem school students will become spelling bee champs?",
  title: "See how you can continue helping your students reach their full potential.",
  description: "It just takes one word to lead a lifetime of learning and growth."
} %>

<div class="container">
  <h1 class="display-4 spe-bee-redange">
    Contact Us
  </h1>
  <p class="lead">
    We'd love to hear from you whether it's a question, comment, or concern
    and will respond within one business day.
    All fields below are required.
  </p>
  <div class="bg-light p-3">
    <%= render "contact_us_mailer/form" %>
  </div>
</div>

app/views/spelling_bee/index.html.erb
<% title "Harlem Spelling Bee - Promoting literacy and education in the Harlem community." %>
<% description "Learn more about the very exciting Harlem Spelling Bee competitions." %>
<% set_meta_tags keywords: %w[harlem spelling bee competition fun schools education vocabulary vocab literacy english language study dictionary words games notebook] %>
<% set_meta_tags og: {
  title: "Learn more about the very exciting Harlem Spelling Bee competitions.",
	description: "Designed with academic vocabulary research and gamification, Leksi helps students master new words."
} %>
<% set_meta_tags twitter: {
  card: "Which Harlem school students will become spelling bee champs?",
  title: "Learn more about the very exciting Harlem Spelling Bee competitions.",
  description: "Learn more about the very exciting Harlem Spelling Bee competitions."
} %>

<section id="spe-bee-index-hero">
  <div class="header">
    <h2 class="spe-bee-redange">
      <%= icon "star" %> Leksi Presents <%= icon "star" %>
    </h2>
    <h1 class="display-1">The Harlem Spelling Bee</h1>
    <h3 class="mt-4 mb-4">
      Giving Harlem Students a Chance to Bee Champions
    </h5>
    <%= link_to spelling_bee_competition_path(anchor: "enroll"),
                role: "button",
                class: "btn btn-success btn-lg",
                title: "Enroll Students for the 2nd Harlem Spelling Bee!" do
    %>
      <%= icon "users" %>
      Register Students Today
    <% end %>
    <%= render "static_pages/mailing_list.html.erb" %>
  </div>
</section>
<section class="spee-bee-trail-section text-center">
  <div class="container pb-5">
    <div class="row">
      <div class="col-md-8 mx-auto">
        <h2>About the Bee<div></div></h2>
        <p class="lead">
          The
          <%= link_to "Leksi",
                      root_path,
                      title: "Visit the Leksi homepage."
          %>
          Harlem Spelling Bee is about more than remembering a few words.
          It’s a challenge that teaches students they can do anything if
          they’re willing to set their mind to it. And if they can study hard
          enough to become Finalists at the Main Event, then there is nothing
          out of their reach.
        </p>
        <p>
          <%= link_to "Learn More",
                      spelling_bee_about_path,
                      class: "btn btn-outline-primary btn-lg",
                      role: "button",
                      title: "Learn more about the history and mission."
          %>
          <%= link_to "Competition Details",
                      spelling_bee_competition_path,
                      class: "btn btn-outline-primary btn-lg",
                      role: "button",
                      title: "Learn more about the Competition."
          %>
        </p>
      </div>
    </div>
  </div>
</section>
<section class="pt-5">
  <div class="container">
    <div class="row text-center lead">
      <div class="col-md-6">
        <div class="card mb-3">
          <div class="card-body">
            <h1 class="spe-bee-redange">
              <%= icon "user-circle" %>
              Teachers
            </h1>
            <p>
              Give your students a chance to expand their knowledge and become a
              Bee Champion.
            </p>
            <%= link_to "Enroll Today",
                        spelling_bee_teachers_path,
                        role: "button",
                        class: "btn btn-primary btn-lg",
                        title: "Support the Harlem Spelling Bee"
            %>
          </div>
        </div>
      </div>
      <div class="col-md-6">
        <div class="card">
          <div class="card-body">
            <h1 class="spe-bee-redange">
              <%= icon "handshake-o" %> Sponsors
            </h1>
            <p>
              Instill a love of education in Harlem.
            </p>
            <%= link_to "Support the Bee",
                        spelling_bee_sponsors_path,
                        role: "button",
                        class: "btn btn-primary btn-lg",
                        title: "Support the Harlem Spelling Bee"
            %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/spelling_bee/parents.html.erb
<% title "Harlem Spelling Bee - Promoting literacy and education in the Harlem community." %>
<% description "See how you can continue helping your students reach their full potential." %>
<% set_meta_tags keywords: %w[harlem spelling bee competition fun schools education vocabulary vocab literacy english language study dictionary words games notebook] %>

<% set_meta_tags og: {
  title: "See how you can continue helping your students reach their full potential.",
	description: "Designed with academic vocabulary research and gamification, Leksi helps students master new words."
} %>

<% set_meta_tags twitter: {
  card: "Which Harlem school students will become spelling bee champs?",
  title: "See how you can continue helping your students reach their full potential.",
  description: "It just takes one word to lead a lifetime of learning and growth."
} %>

<div class="container">
  <h1 class="display-4 spe-bee-redange mb-5">
    <%= icon "globe" %>
    Parents
  </h1>
  <p>
    Help your students reach their fullest potential by enrolling in the
    2nd Harlem Spelling Bee.
  </p>
  <%= render "spelling_bee/q_and_a/questions_parents" %>
  <section class="spe-bee-enroll">
    <div class="card card-inverse card-primary mb-3 text-center">
      <div class="card-body">
        <h1>Enroll Your Students</h1>
        <p>
          It just takes one word to lead a lifetime of learning and growth.
        </p>
      </div>
    </div>
  </section>
</div>

app/views/spelling_bee/sponsors.html.erb
<% title "Harlem Spelling Bee - Promoting literacy and education in the Harlem community." %>
<% description "See how you can continue helping your students reach their full potential." %>
<% set_meta_tags keywords: %w[harlem spelling bee competition fun schools education vocabulary vocab literacy english language study dictionary words games notebook] %>

<% set_meta_tags og: {
  title: "See how you can continue helping your students reach their full potential.",
	description: "Designed with academic vocabulary research and gamification, Leksi helps students master new words."
} %>

<% set_meta_tags twitter: {
  card: "Which Harlem school students will become spelling bee champs?",
  title: "See how you can continue helping your students reach their full potential.",
  description: "It just takes one word to lead a lifetime of learning and growth."
} %>
<div class="sponsors jumbotron mb-3">
  <div class="row">
    <div class="col-md-8 mx-auto">
      <h1 class="display-4">
        <b>Sponsors</b>, Make a Difference. Leave Your Mark in Harlem
      </h1>
      <p class="lead mb-5">
        Support the education of students in the Harlem community and change
        their lives.
      </p>
      <%= link_to "Sponsor the Bee",
                  spelling_bee_sponsors_path(anchor: "enroll"),
                  role: "button",
                  class: "btn btn-success btn-lg",
                  title: "Make an impact and sponsor the Harlem Spelling Bee."
      %>
      <p class="mb-5">&nbsp;</p>
    </div>
  </div>
</div>
<div class="container">
  <%= render "spelling_bee/q_and_a/sponsors" %>
  <%= render "spelling_bee/enroll" %>
</div>