config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "about-us" => "static_pages#about_us"
  get "research" => "static_pages#research"
  get "our-approach" => "static_pages#our_approach"
  get "results" => "static_pages#results"
  get "terms-of-use" => "static_pages#terms_of_use"
  get "privacy-policy" => "static_pages#privacy_policy"

  controller :blog do
    get "blog" => :index
    get "blog/first-harlem-spelling-bee" => :june_19_2017_first_harlem_spelling_bee
    get "blog/six-words-that-dont-mean-what-you-think" => :june_19_2017_six_words_that_dont_mean_what_you_think
    get "blog/about-our-name" => :june_19_2017_about_our_name
  end

  controller :spelling_bee do
    get "spelling-bee" => :index
    get "spelling-bee/about" => :about
    get "spelling-bee/competition" => :competition
    get "spelling-bee/teachers" => :teachers
    get "spelling-bee/sponsors" => :sponsors
    get "spelling-bee/contact-us" => :contact_us
  end

  get "feedback" => "current_users#feedback"
  get "dictionary" => "searches#dictionary"
  get "searches/section"
  get "searches/random"
  get "search_results" => "searches#results"
  get "stats" => "current_users#stats"
  get "freestyles" => "current_users#freestyles"
  get "notebook" => "my_leksi#index"
  get "my_leksi/words"
  get "myLeksi/:id" => "my_leksi#show"
  get "gamezone" => "games#gamezone"
  get "fundamentals" => "games#fundamentals"
  get "jeopardy" => "games#jeopardy"
  get "freestyle" => "games#freestyle"
  get "games/new"
  get "signup" => "users#new"
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  post "static_pages/contact_us"
  post "games/email_freestyle"
  delete "logout" => "sessions#destroy"
  resources :users, except: [:index]
  resources :words, only: [:show]

  resources :words do
    resources :examples
  end

  get "thesaurus/:word_name" => "words#thesaurus"

  resources :words do
    resources :meaning_alts, only: [:index]
  end

  resources :words do
    resources :example_non_examples, only: [:index]
  end

  resources :words do
    resources :sent_stems, only: [:index]
  end

  resource :user_word, only: [:create, :update, :destroy]
  resource :jeopardy_game, only: [:create, :update, :destroy]

  resource :freestyle do
    member do
      post "ex_non_ex"
      post "sent_stem"
      post "word_rel"
      post "leksi_tale"
      post "describe_me"
      post "in_my_life"
    end
  end

  resource :game_stat do
    member do
      post "generic_game"
    end
  end

  resource :jeopardy_result, only: [:update]
  resources :tags, only: [:index]
  resource :user_tag, only: [:create, :edit, :destroy]
  resource :word_tag, only: [:create, :destroy]
  resource :user_word_tag, only: [:create, :edit, :destroy]

  namespace :games do
    resources :word_relationships, only: [:index]
    resources :describe_mes, only: [:index]
    resources :spellmasters, only: [:index]
  end

  namespace :school do
    root "classrooms#index"
    get "example_non_examples/fourth" => "example_non_examples#fourth_grade"
    get "decisions_decisions/fourth" => "meaning_alts#fourth_grade"
    get "example_non_examples/second" => "example_non_examples#second_grade"
    get "example_non_examples/fifth" => "example_non_examples#fifth_grade"
    get "example_non_examples/sixth" => "example_non_examples#sixth_grade"
    get "search" => "searches#search"
    get "search_words_for_students" => "searches#student_words"
    get "stats" => "stats#index"
    get "add_words" => "students#add_words"

    resources :activities, only: [:index]

    resources :classrooms do
      resources :students
    end

    resources :words, except: [:show, :destroy]
    resource :add_words_for_student, only: [:update]
    resource :reset_passwords, only: [:update]

    resources :example_non_examples

    resources :word do
      resources :example_non_examples
    end

    resources :meaning_alts

    resources :word do
      resources :meaning_alts
    end

    resources :freestyles do
      resources :comments
    end

    resources :tags
  end

  namespace :admin do
    root "admins#home"
    get "home" => "admins#home"
    get "stats" => "admins#stats"
    resources :users
    resources :words
    resources :classrooms
    resources :meaning_alts
    resources :example_non_examples
    resources :tags
    resources :freestyles
  end
end

app/controllers/my_leksi_controller.rb
class MyLeksiController < ApplicationController
	before_action :logged_in_user

	def index
		@user_words = UserWord.where(user: current_user)
												  .alphabetical
												  .includes(:word)
	end

	def show
		@word = Word.find(params[:id])
		@user_word = UserWord.object(current_user, @word)
	end

	def words
		@target_word = Word.find(params[:word_id])
		@words = if current_user.num_words > 3
			UserWord.where(user: current_user)
							.includes(:word)
							.map(&:word)
		else
			Word.random(4)
		end

		render json: @words << @target_word
	end

	private

	def logged_in_user
		unless logged_in?
			flash[:danger] = "Please log in first."
			redirect_to login_url
		end
	end

end

app/views/my_leksi/_current_game.html.erb
<small>
<% if user_word.all_freestyles_completed? %>
	<span class="text-info">
<% elsif user_word.fundamental_not_completed? %>
	<span class="text-danger">
<% elsif user_word.jeopardy_not_completed? %>
	<span class="text-warning">
<% elsif user_word.jeopardy_completed? %>
	<span class="text-success">
<% end %>
	Level
		<%= user_word.current_game %>
	</span>
</small>

app/views/my_leksi/_freestyle_responses.html.erb
<% if logged_in? %>
  <% if user_word.all_freestyles_completed? %>
    <div class="panel panel-default">
      <div class="panel-body">
        <p class="lead">
          <i class="fa fa-commenting"></i>
          Freestyle Game Responses</p>
        <div class="row">
          <div class="col-xs-6">
            <h5>Semantic Map</h5>
            <% semantic_responses(user_word).each_with_index do |r, i| %>
            <p>
              <%= i + 1 %>. <%= r %>
            </p>
            <% end %>
          </div>
          <div class="col-xs-6">
            <h5>Word Map</h5>
            <% word_map_responses(user_word).each_with_index do |r, i| %>
            <p>
              <%= i + 1 %>. <%= r %>
            </p>
            <% end %>
          </div>
        </div>
        <hr>
        <div>
          <h5>Definition Map</h5>
          <% definition_map_responses(user_word).each_with_index do |r, i| %>
          <p>
            <%= i + 1 %>. <%= r %>
          </p>
          <% end %>
        </div>
        <hr>
        <div>
          <h5>Sentence Examples</h5>
          <% sentence_responses(user_word).each_with_index do |r, i| %>
          <p>
            <%= i + 1 %>. <%= r %>
          </p>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/my_leksi/_knowledge_key.html.erb
<div class="panel panel-default word-of-knowledge-container">
	<div class="pull-right">
		<i class="fa fa-question-circle-o pointer fa-2x dark-gray"
			 data-toggle="modal"
			 data-target="#word-tree-of-knowledge-modal"></i>
	</div>
	<p>
		<strong>Word-Tree of Knowledge</strong>
	</p>
	<%= image_tag(
		"strength4_key.png",
		alt: "Still strong",
		title: "Still strong")
	%>
	&nbsp; Still strong
	<hr>
	<%= image_tag(
		"strength3_key.png",
		alt: "Pretty good",
		title: "Pretty good")
	%>
	&nbsp; Pretty good
	<hr>
	<%= image_tag(
		"strength2_key.png",
		alt: "Time to practice",
		title: "Time to practice")
	%>
	&nbsp; Time to practice
	<hr>
	<%= image_tag(
		"strength1_key.png",
		alt: "Overdue",
		title: "Overdue")
	%>
	&nbsp; Overdue
</div>
<div class="modal fade"
		 id="word-tree-of-knowledge-modal"
		 tabindex="-1"
		 role="dialog"
		 aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button"
								class="close"
								data-dismiss="modal"
								aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
        <h4 class="modal-title" id="myModalLabel">
					The Word-Tree of Knowledge
				</h4>
      </div>
      <div class="modal-body">
				<p>
					This shows how well you know a word: the more times you play our
					games, you grow your knowledge of the word.
				</p>
				<p>
					Your goal is to grow each word and earn the Apple Tree:
					<%= image_tag(
						"strength4.png",
						alt: "Gold Apple Tree",
						title: "Gold Apple Tree")
					%>
				</p>
				<p>
					Also, we'll let you know when it's time to practice a word so you
					don't forget what it means and how to use it.
				</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default"
								data-dismiss="modal">
					Close
				</button>
      </div>
    </div>
  </div>
</div>

app/views/my_leksi/_level_completion.html.erb
<% if user_word.freestyle_completed? %>
	<span class="text-info">
<% elsif user_word.fundamental_not_completed? %>
	<span class="text-danger">
<% elsif user_word.jeopardy_not_completed? %>
	<span class="text-warning">
<% elsif user_word.jeopardy_completed? %>
	<span class="text-success">
<% end %>
		<%= user_word.current_game %>
		<i class="fa fa-trophy"></i>
	</span>

app/views/my_leksi/_no_words_guide.html.erb
<div class="jumbotron mt-3">
  <h1 class="display-3">Welcome to Leksi!</h1>
  <p class="lead">
    <%= emoji "fist" %> We will make you <%= emoji "fist" %>
    <br>
    <%= emoji "nerd_face" %> smarter
    <%= emoji "nerd_face" %>
    <br>
    <%= emoji "chart_with_upwards_trend" %> and earn
    better grades <%= emoji "chart_with_upwards_trend" %>.
  </p>
  <p>
    To get going, click the button below to add new words to your Notebook.
  </p>
  <p>
    <%= link_to "Start",
                dictionary_path,
                class: "btn btn-lg btn-success",
                role: "button"
    %>.
  </p>
</div>

app/views/my_leksi/_remove.html.erb
<div>
  <p class="text-muted">
    You added this word <%= time_ago_in_words(user_word.created_at) %> ago.
  </p>
  <%= button_to user_word_path(id: user_word.id),
    class: "btn btn-outline-secondary btn-sm",
    method: :delete do
  %>
    <i class="fa fa-trash"></i>
    Remove Word
  <% end %>
</div>

app/views/my_leksi/_show_game_zone.html.erb
<div class="card mb-3">
	<div class="card-body pb-1">
		<h5 class="card-title"><i class="fa fa-gamepad"></i> Game Zone</h5>
	</div>
	<ul class="list-group list-group-flush">
		<li class="list-group-item">
			<%= link_to "Level 1: Spelling Speed",
									fund_game_link(word_id, 1),
									class: "text-danger",
									remote: true
			%>
		</li>
		<li class="list-group-item">
			<%= link_to "Level 2: Jumbled Letters",
									fund_game_link(word_id, 2),
									class: "text-danger",
									remote: true
			%>
		</li>
		<li class="list-group-item">
			<%= link_to "Level 3: Say It Right",
									fund_game_link(word_id, 3),
									class: "text-danger",
									remote: true
			%>
		</li>
		<li class="list-group-item">
			<%= link_to "Level 4: Decisions, Decisions",
									fund_game_link(word_id, 4),
									class: "text-danger",
									remote: true
			%>
		</li>
		<li class="list-group-item">
			<%= link_to "Level 5: Examples/Non-Examples",
									fund_game_link(word_id, 5),
									class: "text-danger",
									remote: true
			%>
		</li>
		<li class="list-group-item">
			<%= link_to "Level 7: Jeopardy",
									jeop_game_link(word_id),
									class: "text-warning",
									remote: true
			%>
		</li>
		<li class="list-group-item text-muted">
			Match 'Em All
			<%#= link_to "Level 8: Match \'Em All",
									jeop_game_link(word_id),
									class: "text-warning",
									remote: true
			%>
		</li>
	  <li class="list-group-item">
			<%= link_to "Level 9: Sentence Stems",
									free_game_link(word_id, 9),
									class: "text-success",
									remote: true
			%>
		</li>
	  <li class="list-group-item">
			<%= link_to "Level 10: Word Relationships",
									free_game_link(word_id, 10),
									class: "text-success",
									remote: true
			%>
		</li>
	  <li class="list-group-item">
			<%= link_to "Level 11: Leksi Tale",
									free_game_link(word_id, 11),
									class: "text-success",
									remote: true
			%>
		</li>
	  <li class="list-group-item">
			<%= link_to "Level 12: Describe Me, Describe Me Not",
									free_game_link(word_id, 12),
									class: "text-success",
									remote: true
			%>
		</li>
	  <li class="list-group-item text-info">
			<%= link_to "Level X: In My Life",
									free_game_link(word_id, 13),
									class: "text-info",
									remote: true
			%>
		</li>
	</ul>
</div>

app/views/my_leksi/_tag.html.erb
<div class="mb-3">
	<h2>
		<small>
			<%= link_to "/myTags/#{tag.id}" do %>
				<%= tag.name %>
			<% end %>
		</small>
	</h2>
	<%= render "tags/remove_tag_btn_word_show_page", word: word, tag: tag %>
</div>

app/views/my_leksi/_tags.html.erb
<div class="card mb-3">
	<div class="card-body">
		<h5 class="card-title">
			<i class="fa fa-tag"></i>
			Tags
		</h5>
		<% if current_user.has_tags? %>
			<%= render "my_leksi/tags_form", word: word %>
			<hr>
			<% if tags_exist?(current_user, word) %>
				<% tags_for(current_user, word).each do |tag| %>
					<%= render "my_leksi/tag", tag: tag, word: word %>
				<% end %>
			<% else %>
				<small class="text-muted">
					None
				</small>
			<% end %>
		<% else %>
			<small class="text-muted">
				<%= link_to "Create your first Tag", new_tag_path %>
				to organize your words.
			</small>
		<% end %>
	</div>
</div>

app/views/my_leksi/_tags_form.html.erb
<%= form_for :user_word_tag,
						 url: user_word_tag_path,
						 method: :post do |f|
%>
	<%= hidden_field_tag :id, word.id %>
	<%= f.label :tag_id, "Tags", class: "sr-only" %>
	<%= f.collection_select :tag_id,
													unused_tags(current_user, word),
													:id,
													:name,
													{ prompt: "Select one" },
													{ class: "form-control" }
	%>
	<%= f.button class: "btn btn-primary btn-block" do %>
		<%= icon "save" %>
		Tag This Word
	<% end %>
<% end %>

app/views/my_leksi/index.html.erb
<% title "View and master all of the words in your personal list." %>
<% description "Designed with vocabulary academic research and gamification, Leksi helps students master new words." %>
<% set_meta_tags keywords: "vocabulary notebook wordlist word list vocab research study dictionary words" %>

<h1 class="mb-5"><%= emoji "notebook" %> Notebook</h1>

<% if current_user.has_words? %>
  <div class="card bg-light mb-4">
    <%= link_to "#collapse-need-help",
                class: "text-dark",
                "data-toggle": "collapse",
                "aria-expanded": "false",
                "aria-controls": "collapse-need-help",
                title: "Click to get help for this page." do
    %>
      <div class="card-header">
        <%= icon "question-circle" %>
        Need Help?
      </div>
    <% end %>
    <div class="collapse card-body text-muted" id="collapse-need-help">
      <%= icon "lightbulb-o" %> Tip #1: click a word to see more details or
      remove it from your Notebook
      <br>
      <%= icon "lightbulb-o" %> Tip #2: click the game controller to play
      the activities for a word
      <br>
      <%= icon "lightbulb-o" %> Tip #3: a thumbs up means you
      completed the activities for that word
    </div>
  </div>

  <% @user_words.includes(:user_tags).each do |user_word| %>
    <div class="notebook-row mb-3">
      <% word = user_word.word %>
      <h1 class="display-5 mb-1">
        <%= play_funds_game(word.id) %>
        <%= link_to "#collapse#{word.id}",
                    class: "text-dark",
                    "data-toggle": "collapse",
                    "aria-expanded": "false",
                    "aria-controls": "collapse#{word.id}",
                    title: "Click to see the meaning of #{word.name}." do
        %>
          <%= word.name %>
        <% end %>

        <% user_word.user_tags.each do |user_tag| %>
          <span class="notebook badge badge-secondary">
            <%= emoji "bookmark_tabs" %>
            <%= user_tag.tag.name %>
          </span>
        <% end %>

        <p class="collapse lead" id="collapse<%= word.id %>">
          <span class="text-muted"><%= word.part_of_speech %></span>
          <%= array_of(word, "definition").first %>
          <br>
          <br>
          <%= link_to user_word_path(id: user_word.id),
                      role: "button",
                      class: "btn btn-danger btn-sm",
                      title: "Remove this word from your Notebook",
                      method: :delete do
          %>
            <%= icon "trash" %> Remove
          <% end %>
        </p>
      </h1>
    </div>
  <% end %>
  <!-- Show different colors based on current game -->
  <%#= render "my_leksi/index_word", user_word: user_word, word: user_word.word %>
<% else %>
  <%= render "my_leksi/no_words_guide" %>
<% end %>

app/views/my_leksi/show.html.erb
<% title "Words: #{@word.name}" %>
<% provide(:header, "Words") %>

<div class="row">
	<div class="col-md-8">
		<div class="row">
			<div class="col-md-6">
				<%= render "words/definitions", word: @word %>
			</div>
			<div class="col-md-6">
				<%= render "words/examples", word: @word %>
			</div>
		</div>
		<div class="row">
			<div class="col-md-6">
				<%= render "words/synonyms", word: @word %>
			</div>
			<div class="col-md-6">
				<%= render "words/antonyms", word: @word %>
			</div>
		</div>
		<div class="row">
			<div class="col-md-6">
				<%= render "my_leksi/tags", word: @word %>
			</div>
		</div>
	</div>
	<div class="col-md-4">
		<%= render "my_leksi/show_game_zone", word_id: @word.id %>
	</div>
</div>
<div class="card text-center mb-3">
	<div class="card-body">
		<%= render "my_leksi/remove", word: @word, user_word: @user_word %>
	</div>
</div>