config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "about-us" => "static_pages#about_us"
  get "research" => "static_pages#research"
  get "our-approach" => "static_pages#our_approach"
  get "results" => "static_pages#results"
  get "terms-of-use" => "static_pages#terms_of_use"
  get "privacy-policy" => "static_pages#privacy_policy"

  controller :blog do
    get "blog" => :index
    get "blog/first-harlem-spelling-bee" => :june_19_2017_first_harlem_spelling_bee
    get "blog/six-words-that-dont-mean-what-you-think" => :june_19_2017_six_words_that_dont_mean_what_you_think
    get "blog/about-our-name" => :june_19_2017_about_our_name
  end

  controller :spelling_bee do
    get "spelling-bee" => :index
    get "spelling-bee/about" => :about
    get "spelling-bee/competition" => :competition
    get "spelling-bee/teachers" => :teachers
    get "spelling-bee/sponsors" => :sponsors
    get "spelling-bee/contact-us" => :contact_us
  end

  get "feedback" => "current_users#feedback"
  get "dictionary" => "searches#dictionary"
  get "searches/section"
  get "searches/random"
  get "search_results" => "searches#results"
  get "stats" => "current_users#stats"
  get "freestyles" => "current_users#freestyles"
  get "notebook" => "my_leksi#index"
  get "my_leksi/words"
  get "myLeksi/:id" => "my_leksi#show"
  get "gamezone" => "games#gamezone"
  get "fundamentals" => "games#fundamentals"
  get "jeopardy" => "games#jeopardy"
  get "freestyle" => "games#freestyle"
  get "games/new"
  get "signup" => "users#new"
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  post "static_pages/contact_us"
  post "games/email_freestyle"
  delete "logout" => "sessions#destroy"
  resources :users, except: [:index]
  resources :words, only: [:show]

  resources :words do
    resources :examples
  end

  get "thesaurus/:word_name" => "words#thesaurus"

  resources :words do
    resources :meaning_alts, only: [:index]
  end

  resources :words do
    resources :example_non_examples, only: [:index]
  end

  resources :words do
    resources :sent_stems, only: [:index]
  end

  resource :user_word, only: [:create, :update, :destroy]
  resource :jeopardy_game, only: [:create, :update, :destroy]

  resource :freestyle do
    member do
      post "ex_non_ex"
      post "sent_stem"
      post "word_rel"
      post "leksi_tale"
      post "describe_me"
      post "in_my_life"
    end
  end

  resource :game_stat do
    member do
      post "generic_game"
    end
  end

  resource :jeopardy_result, only: [:update]
  resources :tags, only: [:index]
  resource :user_tag, only: [:create, :edit, :destroy]
  resource :word_tag, only: [:create, :destroy]
  resource :user_word_tag, only: [:create, :edit, :destroy]

  namespace :games do
    resources :word_relationships, only: [:index]
    resources :describe_mes, only: [:index]
    resources :spellmasters, only: [:index]
  end

  namespace :school do
    root "classrooms#index"
    get "example_non_examples/fourth" => "example_non_examples#fourth_grade"
    get "decisions_decisions/fourth" => "meaning_alts#fourth_grade"
    get "example_non_examples/second" => "example_non_examples#second_grade"
    get "example_non_examples/fifth" => "example_non_examples#fifth_grade"
    get "example_non_examples/sixth" => "example_non_examples#sixth_grade"
    get "search" => "searches#search"
    get "search_words_for_students" => "searches#student_words"
    get "stats" => "stats#index"
    get "add_words" => "students#add_words"

    resources :activities, only: [:index]

    resources :classrooms do
      resources :students
    end

    resources :words, except: [:show, :destroy]
    resource :add_words_for_student, only: [:update]
    resource :reset_passwords, only: [:update]

    resources :example_non_examples

    resources :word do
      resources :example_non_examples
    end

    resources :meaning_alts

    resources :word do
      resources :meaning_alts
    end

    resources :freestyles do
      resources :comments
    end

    resources :tags
  end

  namespace :admin do
    root "admins#home"
    get "home" => "admins#home"
    get "stats" => "admins#stats"
    resources :users
    resources :words
    resources :classrooms
    resources :meaning_alts
    resources :example_non_examples
    resources :tags
    resources :freestyles
  end
end

app/controllers/school/searches_controller.rb
class School::SearchesController < BaseSchoolController
  def search
  end

  def student_words
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def dictionary
  end

  def random
    @word = Word.random(1).first

    respond_to do |format|
      format.js { render template: "searches/words/random.js.erb" }
    end
  end

  def section
    @section = params[:name]
    @word_groups = Word.send(@section).group_by(&:name)

    respond_to do |format|
      format.js { render template: "searches/words/section.js.erb" }
    end
  end

  def results
    @search = params[:search]
    @account_type = params[:account_type]

    begin
      if @search
        if @search.empty?
          @word_groups = nil
          @error = "Please type in a word for us to search."
        else
          @input_words = @search.split(",").map(&:strip)
          @word_groups = @input_words.map { |w| Word.define(w) }
                                     .flatten
                                     .group_by { |w| w.name }
        end

        respond_to do |format|
          format.js
        end
      end
    rescue WordsApi::NoWordError => e
      @error = e.message
    end
  end
end

app/views/searches/_dict_display.html.erb
<dt class="col-sm-3">
	<%= word.name %>
</dt>
<dd class="col-sm-6">
	<span class="text-muted"><%= word.part_of_speech %></span>
	<%= array_of(word, "definition").first %>
</dd>
<dd class="col-sm-3" data-word-id="<%= word.id %>">
	<%= render "searches/dict_display_btns", word: word,
																					 account_type: account_type
  %>
</dd>

app/views/searches/_dict_display_btns.html.erb
<% if logged_in? %>
	<% if account_type == "student" %>
		<% if current_user.has_word?(word) %>
			<div class="alert alert-info">
				<%= icon "info-circle" %> You already saved this in your Notebook.
			</div>
		<% else %>
			<p>
				<%= link_to user_word_path(word_id: word.id),
										class: "btn btn-success",
										method: :post,
										remote: true do
				%>
					<%= icon "plus-circle" %>
					Add to Notebook
				<% end %>
			</p>
		<% end %>
	<% elsif account_type == "teacher" %>
		<button type="button"
						class="btn btn-primary dropdown-toggle"
						data-toggle="dropdown"
						aria-haspopup="true"
						aria-expanded="false">
			<%= icon "bars" %> Actions
		</button>
		<div class="dropdown-menu">
			<%= link_to new_school_word_example_non_example_path(word, Example.new),
					class: "dropdown-item",
					title: "Create New Example/Non-Example" do
			%>
				Create New Example/Non-Example
				<%= display_content_status(word.has_ex_non_exs?) %>
			<% end %>


			<%= link_to new_school_word_meaning_alt_path(word, MeaningAlt.new),
					class: "dropdown-item",
					title: "Create New Decisions, Decision" do
			%>
				Create New Decisions, Decisions
				<%= display_content_status(word.has_meaning_alts?) %>
			<% end %>
			<div class="dropdown-divider"></div>
			<%= link_to "Add to Notebook",
					"#",
					"data-word-id": word.id,
					"data-word-name": word.name,
					class: "dropdown-item awfs-add-word-btn",
					title: "Add to Notebook"
			%>
		</div>
	<% end %>
<% end %>

app/views/searches/_form.html.erb
<div class="input-group input-group-lg">
  <%= label_tag :'input-search',
                "Search",
                class: "form-control-label sr-only"
  %>
  <%= text_field_tag :search,
                     params[:search],
                     type: "search",
                     class: "form-control",
                     id: "input_search",
                     placeholder: "Type word(s) here",
                     autofocus: true
  %>
  <span class="input-group-btn">
    <%= button_tag type: "submit",
                   "data-account-type": account_type,
                   class: "btn btn-primary",
                   id: "search-btn" do
    %>
      <%= icon "search" %> Look Up
    <% end %>
  </span>
</div>
<p class="form-text text-muted">
  <small>
    <%= icon "lightbulb-o" %> Tip: Look up multiple words by
    separating them with commas, for example: <em>one, two, three</em>
  </small>
</p>

app/views/searches/_guide.html.erb
<div class="modal fade"
		 id="search-info-guide-modal"
		 tabindex="-1"
		 role="dialog"
		 aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button"
								class="close"
								data-dismiss="modal"
								aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
        <h4 class="modal-title" id="myModalLabel">How to Look Up Words</h4>
      </div>
      <div class="modal-body">
				<div class="row" id="search-guide">
					<div class="col-sm-6">
						<span class="badge">1</span>
						Type a word in the box and tap the search-button to
						look up a word that you don't know. Or click
						<em>I'm feeling adventurous</em>
						to let us find one for you!
					</div>
					<br>
					<div class="col-sm-6">
						<span class="badge">2</span>
						Tap "<i class="fa fa-plus-circle"></i>"
						to stay on this page and continue looking up and defining words or
						"<i class="fa fa-gamepad"></i>"
						to begin playing immediately!
					</div>
				</div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">
					Close
				</button>
      </div>
    </div>
  </div>
</div>

app/views/searches/_results.html.erb
<% if word_groups.nil? %>
	<div class="alert alert-danger"><%= error %></div>
<% else %>
		<% word_groups.each_with_index do |(name, words), i| %>
				<% words.take(10).each do |word| %>
				<dl class="notebook row">
					<%= render "searches/dict_display", word: word,
																							account_type: account_type
          %>
				</dl>
				<% end %>
		<% end %>
<% end %>

app/views/searches/_user_play.html.erb
<%= link_to user_word_path(search_btn: :play, word_id: word.id),
						class: "btn btn-success btn-lg",
						method: :post,
						remote: true do
%>
	<i class="fa fa-play-circle"></i> Play
<% end %>

app/views/searches/dictionary.html.erb
<% title "Dictionary: Look up words or choose one randomly or from a list." %>
<% description "Explore new words to add to your Notebook. Then master them!" %>
<% set_meta_tags keywords: "learn education vocabulary vocab research engage fun langauge literacy english language study dictionary words flashcards games list notebook" %>
<% set_meta_tags og: {
  title:    "Dictionary: Look up words or choose one randomly or from a list.",
	description: "Look up words you don\'t know or select ones from a specific list"
} %>
<% set_meta_tags twitter: {
  card: "Learn vocabulary free, without ads or hidden charges. It's simple, fun, and works.",
  title: "Leksi Dictionary",
  description: "Look up words you don\'t know or select ones from a specific list"
} %>

<h1><%= icon("search") %> Dictionary</h1>
<div class="mb-3 card bg-light">
  <div class="card-body">
    <div class="btn-group mb-3"
         role="group"
         aria-label="Dictionary filter">
      <%= link_to searches_random_path, role: "button",
                                        class: "btn btn-secondary",
                                        remote: true do
      %>
        Random
      <% end %>

      <div class="btn-group" role="group">
        <button id="btnGroupDrop1"
                type="button"
                class="btn btn-secondary dropdown-toggle"
                data-toggle="dropdown"
                aria-haspopup="true"
                aria-expanded="false">
          Grades
        </button>
        <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
          <%= link_to "1st Grade", searches_section_path(name: "first_grade"),
                                   class: "dropdown-item disabled",
                                   remote: true
          %>
          <%= link_to "2nd Grade", searches_section_path(name: "second_grade"),
                                   class: "dropdown-item",
                                   remote: true
          %>
          <%= link_to "3rd Grade", searches_section_path(name: "third_grade"),
                                   class: "dropdown-item",
                                   remote: true
          %>
          <%= link_to "4th Grade", searches_section_path(name: "fourth_grade"),
                                   class: "dropdown-item",
                                   remote: true
          %>
          <%= link_to "5th Grade", searches_section_path(name: "fifth_grade"),
                                   class: "dropdown-item",
                                   remote: true
          %>
          <%= link_to "6th Grade", searches_section_path(name: "sixth_grade"),
                                   class: "dropdown-item",
                                   remote: true
          %>
          <%= link_to "7th Grade", searches_section_path(name: "seventh_grade"),
                                   class: "dropdown-item",
                                   remote: true
          %>
          <%= link_to "8th Grade", searches_section_path(name: "eigth_grade"),
                                   class: "dropdown-item",
                                   remote: true
          %>
        </div>
      </div>
    </div>
    <div class="search-form-container">
      <%= render "searches/form", account_type: "student" %>
    </div>
  </div>
</div>
<div class="search-results-container"></div>

app/views/searches/multiple_words.js.erb
const partial = "<%= j render(partial: 'searches/results', locals: { words: @words }) %>";
$(".search-results-container").hide().html(partial).fadeIn(400);

app/views/searches/results.js.erb
const partial = "<%= j render(partial: 'searches/results', locals: { word_groups: @word_groups, account_type: @account_type, error: @error }) %>";
$(".search-results-container").hide().html(partial).fadeIn(400);